# Generated by Django 4.2.30 on 2026-06-14 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='emergency_phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='medical_history',
        ),
        migrations.RemoveField(
            model_name='test',
            name='normal_range',
        ),
        migrations.RemoveField(
            model_name='test',
            name='sample_type',
        ),
        migrations.RemoveField(
            model_name='test',
            name='turnaround_time',
        ),
    ]
