# Generated by Django 4.2.30 on 2026-06-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_mgmt', '0002_remove_customer_allergies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertest',
            name='is_abnormal',
        ),
        migrations.RemoveField(
            model_name='ordertest',
            name='result_notes',
        ),
        migrations.RemoveField(
            model_name='ordertest',
            name='result_uploaded_at',
        ),
        migrations.RemoveField(
            model_name='ordertest',
            name='result_uploaded_by',
        ),
        migrations.RemoveField(
            model_name='ordertest',
            name='result_value',
        ),
        migrations.RemoveField(
            model_name='testorder',
            name='doctor_name',
        ),
    ]
