# Generated by Django 4.2.30 on 2026-06-18 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_remove_laboratory_approved_at_and_more'),
        ('tests_mgmt', '0003_remove_ordertest_is_abnormal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='lab.laboratory'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='patient_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
