# Generated by Django 4.2.30 on 2026-06-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='email',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='website',
        ),
    ]
